use std::collections::HashMap;
use std::ops::Deref;

use serde::{Deserialize, Serialize};
use zbus::{
    proxy,
    zvariant::{ObjectPath, OwnedObjectPath, OwnedValue, Type, Value},
};

use crate::error::Result;

#[derive(Clone, Debug, Type, PartialEq, Deserialize, Serialize, Value)]
pub struct IconPixmap {
    pub width: i32,
    pub height: i32,
    pub data: Vec<u8>,
}

#[derive(Clone, Debug, Type, PartialEq, Deserialize, Serialize, OwnedValue)]
pub struct ToolTip {
    pub icon_name: String,
    pub icon_pixmap: Vec<IconPixmap>,
    pub title: String,
    pub description: String,
}

#[derive(Deserialize, Serialize, Type, PartialEq, Debug)]
pub(crate) struct MenuLayout {
    pub id: u32,
    pub fields: SubMenuLayout,
}

#[derive(Deserialize, Serialize, Type, PartialEq, Debug)]
pub(crate) struct SubMenuLayout {
    pub id: i32,
    pub fields: HashMap<String, OwnedValue>,
    pub submenus: Vec<OwnedValue>,
}

#[allow(dead_code)]
type GroupProperties = Vec<(i32, HashMap<String, zbus::zvariant::OwnedValue>)>;

#[derive(Deserialize, Serialize, Type, Debug, Clone)]
pub struct PropertiesUpdate<'a> {
    #[serde(borrow)]
    pub(crate) updated: Vec<UpdatedProps<'a>>,
    pub(crate) removed: Vec<RemovedProps<'a>>,
}

#[derive(Deserialize, Serialize, Type, Debug, Clone)]
pub struct UpdatedProps<'a> {
    pub(crate) id: i32,
    #[serde(borrow)]
    pub(crate) fields: HashMap<&'a str, Value<'a>>,
}

#[derive(Deserialize, Serialize, Type, Debug, Clone)]
pub struct RemovedProps<'a> {
    pub(crate) id: i32,
    #[serde(borrow)]
    pub(crate) fields: Vec<&'a str>,
}

pub(crate) struct DBusProps(pub HashMap<String, OwnedValue>);

impl DBusProps {
    /// Gets `key` from the map if present,
    /// downcasting it to type `T`.
    pub fn get<'a, T>(&'a self, key: &str) -> Option<Result<&'a T>>
    where
        T: ?Sized,
        &'a T: TryFrom<&'a Value<'a>>,
        <&'a T as TryFrom<&'a Value<'a>>>::Error: Into<zbus::zvariant::Error>,
    {
        self.0
            .get(key)
            .map(|v| v.downcast_ref().map_err(Into::into))
    }

    /// Gets `key` from the map if present,
    /// interpreting it as a `str`
    /// and converting it to a string.
    pub fn get_string(&self, key: &str) -> Option<Result<String>> {
        self.get::<str>(key).map(|res| res.map(ToString::to_string))
    }

    /// Gets `key` from the map if present,
    /// interpreting it as an `ObjectPath`,
    /// and converting it to a string.
    pub fn get_object_path(&self, key: &str) -> Option<Result<String>> {
        self.get::<ObjectPath>(key)
            .map(|res| res.map(ToString::to_string))
    }
}

pub(crate) trait OwnedValueExt {
    fn to_string(&self) -> Result<String>;
}

impl OwnedValueExt for OwnedValue {
    fn to_string(&self) -> Result<String> {
        self.downcast_ref::<&str>()
            .map(ToString::to_string)
            .map_err(Into::into)
    }
}

impl Deref for DBusProps {
    type Target = HashMap<String, OwnedValue>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// # D-Bus interface proxy for: `com.canonical.dbusmenu`
///
/// This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
/// Source: `protocol/dbus-menu.xml`.
#[proxy(interface = "com.canonical.dbusmenu", assume_defaults = true)]
pub trait DBusMenu {
    /// AboutToShow method
    fn about_to_show(&self, id: i32) -> zbus::Result<bool>;

    /// AboutToShowGroup method
    fn about_to_show_group(
        &self,
        ids: &[i32],
    ) -> zbus::Result<(Vec<i32>, Vec<i32>)>;

    /// Event method
    fn event(
        &self,
        id: i32,
        event_id: &str,
        data: &Value<'_>,
        timestamp: u32,
    ) -> zbus::Result<()>;

    /// EventGroup method
    fn event_group(
        &self,
        events: &[&(i32, &str, &Value<'_>, u32)],
    ) -> zbus::Result<Vec<i32>>;

    /// GetGroupProperties method
    fn get_group_properties(
        &self,
        ids: &[i32],
        property_names: &[&str],
    ) -> zbus::Result<Vec<(i32, HashMap<String, OwnedValue>)>>;

    /// GetLayout method
    fn get_layout(
        &self,
        parent_id: i32,
        recursion_depth: i32,
        property_names: &[&str],
    ) -> zbus::Result<(u32, MenuLayout)>;

    /// GetProperty method
    fn get_property(&self, id: i32, name: &str) -> zbus::Result<OwnedValue>;

    /// ItemActivationRequested signal
    #[zbus(signal)]
    fn item_activation_requested(
        &self,
        id: i32,
        timestamp: u32,
    ) -> zbus::Result<()>;

    /// ItemsPropertiesUpdated signal
    #[zbus(signal)]
    fn items_properties_updated(
        &self,
        updated_props: Vec<(i32, HashMap<&str, Value<'_>>)>,
        removed_props: Vec<(i32, Vec<&str>)>,
    ) -> zbus::Result<()>;

    /// LayoutUpdated signal
    #[zbus(signal)]
    fn layout_updated(&self, revision: u32, parent: i32) -> zbus::Result<()>;

    /// IconThemePath property
    #[zbus(property)]
    fn icon_theme_path(&self) -> zbus::Result<Vec<String>>;

    /// Status property
    #[zbus(property)]
    fn status(&self) -> zbus::Result<String>;

    /// TextDirection property
    #[zbus(property)]
    fn text_direction(&self) -> zbus::Result<String>;

    /// Version property
    #[zbus(property)]
    fn version(&self) -> zbus::Result<u32>;
}

/// # D-Bus interface proxy for: `org.kde.StatusNotifierItem`
///
/// This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
/// Source: `protocol/dbus-status-notifier-item.xml`.
#[proxy(interface = "org.kde.StatusNotifierItem", assume_defaults = false)]
pub trait StatusNotifierItem {
    /// Activate method
    fn activate(&self, x: i32, y: i32) -> zbus::Result<()>;

    /// ContextMenu method
    fn context_menu(&self, x: i32, y: i32) -> zbus::Result<()>;

    /// Scroll method
    fn scroll(&self, delta: i32, orientation: &str) -> zbus::Result<()>;

    /// SecondaryActivate method
    fn secondary_activate(&self, x: i32, y: i32) -> zbus::Result<()>;

    /// NewAttentionIcon signal
    #[zbus(signal)]
    fn new_attention_icon(&self) -> zbus::Result<()>;

    /// NewIcon signal
    #[zbus(signal)]
    fn new_icon(&self) -> zbus::Result<()>;

    /// NewOverlayIcon signal
    #[zbus(signal)]
    fn new_overlay_icon(&self) -> zbus::Result<()>;

    /// NewStatus signal
    #[zbus(signal)]
    fn new_status(&self, status: &str) -> zbus::Result<()>;

    /// NewTitle signal
    #[zbus(signal)]
    fn new_title(&self) -> zbus::Result<()>;

    /// NewToolTip signal
    #[zbus(signal)]
    fn new_tool_tip(&self) -> zbus::Result<()>;

    /// AttentionIconName property
    #[zbus(property)]
    fn attention_icon_name(&self) -> zbus::Result<String>;

    /// AttentionIconPixmap property
    #[zbus(property)]
    fn attention_icon_pixmap(&self) -> zbus::Result<Vec<IconPixmap>>;

    /// AttentionMovieName property
    #[zbus(property)]
    fn attention_movie_name(&self) -> zbus::Result<String>;

    /// Category property
    #[zbus(property)]
    fn category(&self) -> zbus::Result<String>;

    /// IconName property
    #[zbus(property)]
    fn icon_name(&self) -> zbus::Result<String>;

    /// IconPixmap property
    #[zbus(property)]
    fn icon_pixmap(&self) -> zbus::Result<Vec<IconPixmap>>;

    /// IconThemePath property
    #[zbus(property)]
    fn icon_theme_path(&self) -> zbus::Result<String>;

    /// Id property
    #[zbus(property)]
    fn id(&self) -> zbus::Result<String>;

    /// ItemIsMenu property
    #[zbus(property)]
    fn item_is_menu(&self) -> zbus::Result<bool>;

    /// Menu property
    #[zbus(property)]
    fn menu(&self) -> zbus::Result<OwnedObjectPath>;

    /// OverlayIconName property
    #[zbus(property)]
    fn overlay_icon_name(&self) -> zbus::Result<String>;

    /// OverlayIconPixmap property
    #[zbus(property)]
    fn overlay_icon_pixmap(&self) -> zbus::Result<Vec<IconPixmap>>;

    /// Status property
    #[zbus(property)]
    fn status(&self) -> zbus::Result<String>;

    /// Title property
    #[zbus(property)]
    fn title(&self) -> zbus::Result<String>;

    /// ToolTip property
    #[zbus(property)]
    #[allow(clippy::type_complexity)]
    fn tool_tip(&self) -> zbus::Result<ToolTip>;
}

/// # D-Bus interface proxy for: `org.kde.StatusNotifierWatcher`
///
/// This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
/// Source: `protocol/dbus-status-notifier-watcher.xml`.
#[proxy(
    default_service = "org.kde.StatusNotifierWatcher",
    interface = "org.kde.StatusNotifierWatcher",
    default_path = "/StatusNotifierWatcher"
)]
pub trait StatusNotifierWatcher {
    /// RegisterStatusNotifierHost method
    fn register_status_notifier_host(&self, service: &str) -> zbus::Result<()>;

    /// RegisterStatusNotifierItem method
    fn register_status_notifier_item(&self, service: &str) -> zbus::Result<()>;

    /// StatusNotifierHostRegistered signal
    #[zbus(signal)]
    fn status_notifier_host_registered(&self) -> zbus::Result<()>;

    /// StatusNotifierHostUnregistered signal
    #[zbus(signal)]
    fn status_notifier_host_unregistered(&self) -> zbus::Result<()>;

    /// StatusNotifierItemRegistered signal
    #[zbus(signal)]
    fn status_notifier_item_registered(
        &self,
        service: &str,
    ) -> zbus::Result<()>;

    /// StatusNotifierItemUnregistered signal
    #[zbus(signal)]
    fn status_notifier_item_unregistered(
        &self,
        service: &str,
    ) -> zbus::Result<()>;

    /// IsStatusNotifierHostRegistered property
    #[zbus(property)]
    fn is_status_notifier_host_registered(&self) -> zbus::Result<bool>;

    /// ProtocolVersion property
    #[zbus(property)]
    fn protocol_version(&self) -> zbus::Result<i32>;

    /// RegisteredStatusNotifierItems property
    #[zbus(property)]
    fn registered_status_notifier_items(&self) -> zbus::Result<Vec<String>>;
}
